/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import CONTROL.API;
import MODEL.ListagemDeDados;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SYSTEM N.P
 */
public class Tela extends javax.swing.JPanel {

    /*Criamos a variável Dados do tipo ListagemDeDados, que receberá os dados encontrados usando a API*/
    public ListagemDeDados Dados;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        /*Invocamos o método que fará as configurações iniciais do painel*/
        configuracoesiniciais();
    }

    /*Método que fará as configurações iniciais do painel*/
    public void configuracoesiniciais() {

        /*Definimos que o usuário não vai poder editar os dados dos JTextField's que receberão os dados do clima*/
        jTextField4.setEditable(false);
        jTextField8.setEditable(false);
        jTextField4.setEditable(false);

        jTextField3.setEditable(false);
        jTextField6.setEditable(false);
        jTextField9.setEditable(false);

        jTextField5.setEditable(false);
        jTextField14.setEditable(false);
        jTextField7.setEditable(false);
        jTextField20.setEditable(false);

        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);

        jTextField15.setEditable(false);
        jTextField16.setEditable(false);
        jTextField17.setEditable(false);
        jTextField18.setEditable(false);
        jTextField19.setEditable(false);
        jTextField21.setEditable(false);

        /*Inicialmente não permitimos que o usuário possa interagir com os JRadioButton's, já que a APi ainda não retornou nenhum valor válido*/
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);

    }

    /*Adicionamos a imagem de fundo do painel*/
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            BufferedImage imagem = ImageIO.read(getClass().getResource("/RESOURCES/foto1.PNG"));

            g.drawImage(imagem, 0, 0, this);

        } catch (IOException ex) {
            System.err.println("arquivo não existe no resource");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField13 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1115, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 262, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Umidade:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Latitude:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));
        add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 262, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Longitude:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));
        add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 262, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("É dia:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sensação térmica:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));
        add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 262, -1));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("°F");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clima:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("°C");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, -1));
        add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 120, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 262, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Velocidade Do Vento:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 262, -1));
        add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 262, -1));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 262, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Grau do vento:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 156, -1));
        add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 262, -1));
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 262, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("°C");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, -1, -1));

        jRadioButton5.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("KM/H");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("°F");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, -1));

        jRadioButton6.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("MP/H");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, -1, -1));
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 262, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Região:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jTextField1.setText("Escreva a cidade e aperte o botão de pesquisar à direita");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 416, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informações Principais:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informações Avançadas:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("País:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Temperatura:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hora Local:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 262, -1));
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 262, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("UV:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fuso Horário:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 262, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Visibilidade:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, -1, -1));
        add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 120, -1));

        jRadioButton7.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("Km");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        jRadioButton8.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("Milhas");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Direção Do Vento:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        jLabel17.setText("   ");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 69, 60));
        add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 262, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Última Atualização:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Preciptação:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, -1, -1));
        add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 120, -1));

        jRadioButton9.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("Mm");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, -1, -1));

        jRadioButton10.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("Polegadas");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("*Por favor, não use acentos e/ou caracteres especiais ao digitar o nome da cidade");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    /*Método que mostra o valor da sensação térmica em fahrenheit*/
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed

        /*Setamos o texto do JTextField da sensação térmica em fahrenheit como o seu correspondente valor retornado pela API*/
        jTextField14.setText(Dados.getSensacaotermicaF() + "°F");

        /*Setamos o JRadioButton de fahrenheit como ativado e o de Celsius como desativado*/
        jRadioButton4.setSelected(false);
        jRadioButton3.setSelected(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /*Método que mostra o valor da sensação térmica em Celsius*/
    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

        /*Setamos o texto do JTextField da sensação térmica em Celsius como o seu correspondente valor retornado pela API*/
        jTextField14.setText(Dados.getSensacaotermicaC() + "°C");

        /*Setamos o JRadioButton de Celsius como ativado e o de fahrenheit como desativado*/
        jRadioButton4.setSelected(true);
        jRadioButton3.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /*Método que mostra o valor da temperatura em Celsius*/
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

        /*Setamos o texto do JTextField da temperatura em Celsius como o seu correspondente valor retornado pela API*/
        jTextField5.setText(Dados.getTemperaturaC() + "°C");

        /*Setamos o JRadioButton de Celsius como ativado e o de fahrenheit como desativado*/
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /*Método que mostra o valor da velocidade do vento em km/h*/
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed

        /*Setamos o texto do JTextField da velocidade do vento em km/h como o seu correspondente valor retornado pela API*/
        jTextField13.setText(Dados.getVentoKMH() + "KM/H");

        /*Setamos o JRadioButton de km/h como ativado e o de mp/h como desativado*/
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    /*Método que mostra o valor da temperatura em fahrenheit*/
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed

        /*Setamos o texto do JTextField da temperatura em fahrenheit como o seu correspondente valor retornado pela API*/
        jTextField5.setText(Dados.getTemperaturaF() + "°F");

        /*Setamos o JRadioButton de fahrenheit como ativado e o de Celsius como desativado*/
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /*Método que mostra o valor da velocidade do vento em mp/h*/
    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed

        /*Setamos o texto do JTextField da velocidade do vento em mp/h como o seu correspondente valor retornado pela API*/
        jTextField13.setText(Dados.getVentoMPH() + "MP/H");

        /*Setamos o JRadioButton de mp/h como ativado e o de km/h como desativado*/
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    /*Método que faz a rquisição à API, retorna os valores recebidos e os distribui para seus respectivos lugares*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*Atualizamos a variável Dados com os dados retornado pela requisição à API, já tratados, usando o nome da cidade informado pelo usuário*/
        Dados = API.aplicacaodaAPI(jTextField1.getText());

        /*Verificamos se os dados(nesse caso, foi usado o nome como exemplo, já que toda cidade deve ter um nome) retornados pela APi não são nulos, ou seja, verificamos se a pesquisa retornou um resultado válido e que não houve erros*/
        if (Dados.getNome() != null) {

            /*Inicialmente permitimos que o usuário possa interagir com os JRadioButton's*/
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton3.setEnabled(true);
            jRadioButton4.setEnabled(true);
            jRadioButton5.setEnabled(true);
            jRadioButton6.setEnabled(true);
            jRadioButton7.setEnabled(true);
            jRadioButton8.setEnabled(true);
            jRadioButton9.setEnabled(true);
            jRadioButton10.setEnabled(true);

            /*Adicionamos alguns valores que foram retornados pela API à seus respectivos JTextField's*/
            jTextField4.setText(Dados.getNome());
            jTextField3.setText(Dados.getPais());
            jTextField6.setText(Dados.getHoralocal());
            jTextField5.setText(Dados.getTemperaturaC() + "°C");
            jTextField14.setText(Dados.getSensacaotermicaC() + "°C");
            jTextField7.setText(Dados.getClima());
            jTextField8.setText(Dados.getRegiao());
            jTextField9.setText(Dados.getFusohorario());

            /*Inicialmente selecionamos o primeiro JRadioButton de cada valor que os possui*/
            jRadioButton1.setSelected(true);
            jRadioButton4.setSelected(true);
            jRadioButton5.setSelected(true);
            jRadioButton7.setSelected(true);
            jRadioButton9.setSelected(true);

            /*E desselecionamos o segundo JRadioButton de cada valor que os possui*/
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            jRadioButton6.setSelected(false);
            jRadioButton8.setSelected(false);
            jRadioButton10.setSelected(false);

            /*Adicionamos mais alguns valores que foram retornados pela API à seus respectivos JTextField's*/
            jTextField10.setText(Dados.getLatitude());
            jTextField11.setText(Dados.getLongitude());
            jTextField12.setText(Dados.getE_dia());

            jTextField13.setText(Dados.getVentoKMH() + "KM/H");
            jTextField15.setText(Dados.getGrauvento() + "°");
            jTextField16.setText(Dados.getDirecaovento());

            jTextField17.setText(Dados.getUV());
            jTextField18.setText(Dados.getUmidade() + "%");

            jTextField19.setText(Dados.getVisibilidadeKM() + "Km");

            jTextField20.setText(Dados.getUltimaatualizacao());

            jTextField21.setText(Dados.getPreciptacaomm() + "mm");

            /*Adicionamos o ícone do clima*/
            try {
                /*Pegamos a url retornada pela API e salvamos em uma variável*/
                URL url = new URL(Dados.getIconeclima());

                /*Usamos a url para gerarmos a imagem que será usada e salva como ImageIcon*/
                Image imagem = ImageIO.read(url);

                ImageIcon icon = new ImageIcon(imagem);

                /*Setamos o ícone de um JLabel como o ícone encontrado, tornando a imagem visível*/
                jLabel17.setIcon(icon);

            } catch (MalformedURLException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } /*Caso os dados retornados pela APi sejam nulos, ou seja, caso a pesquisa retornou um resultado inválido e/ou que houve erros*/ else {

            /*Não permitimos que o usuário possa interagir com os JRadioButton's, já que a APi não retornou nenhum valor válido*/
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
            jRadioButton5.setEnabled(false);
            jRadioButton6.setEnabled(false);
            jRadioButton7.setEnabled(false);
            jRadioButton8.setEnabled(false);
            jRadioButton9.setEnabled(false);
            jRadioButton10.setEnabled(false);

            /*Retiramos os dados que estavam nos JTextField's*/
            jTextField1.setText("");

            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            jTextField16.setText("");

            jTextField17.setText("");
            jTextField18.setText("");
            jTextField19.setText("");
            jTextField20.setText("");

            jTextField21.setText("");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /*Método que mostra o valor da visibilidade em km*/
    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed

        /*Setamos o texto do JTextField da visibilidade em km como o seu correspondente valor retornado pela API*/
        jTextField19.setText(Dados.getVisibilidadeKM() + "Km");

        /*Setamos o JRadioButton de km como ativado e o de milhas como desativado*/
        jRadioButton8.setSelected(false);
        jRadioButton7.setSelected(true);


    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /*Método que mostra o valor da visibilidade em milhas*/
    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed

        /*Setamos o texto do JTextField da visibilidade em milhas como o seu correspondente valor retornado pela API*/
        jTextField19.setText(Dados.getVisibilidadeMilhas() + "Milhas");

        /*Setamos o JRadioButton de milhas como ativado e o de km como desativado*/
        jRadioButton8.setSelected(true);
        jRadioButton7.setSelected(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    /*Método que mostra o valor da preciptação em mm*/
    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed

        /*Setamos o texto do JTextField da preciptação em mm como o seu correspondente valor retornado pela API*/
        jTextField21.setText(Dados.getPreciptacaomm() + "mm");

        /*Setamos o JRadioButton de mm como ativado e o de polegadas como desativado*/
        jRadioButton9.setSelected(true);
        jRadioButton10.setSelected(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    /*Método que mostra o valor da preciptação em polegadas*/
    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed

        /*Setamos o texto do JTextField da preciptação em polegadas como o seu correspondente valor retornado pela API*/
        jTextField21.setText(Dados.getPreciptacaoinches() + "polegadas");

        /*Setamos o JRadioButton de polegadas como ativado e o de mm como desativado*/
        jRadioButton9.setSelected(false);
        jRadioButton10.setSelected(true);
    }//GEN-LAST:event_jRadioButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
